name: Full CI/CD Pipeline with ECR Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev --python 3.10

      - name: Run tests
        run: pipenv run pytest

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy on main branch
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      # Docker Build
      - name: Build Docker image
        run: docker build -t ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} .

      # AWS Setup
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ECR Deployment
      - name: Tag and push to ECR
        run: |
          docker tag ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }} ${{ env.ECR_IMAGE_URI }}
          docker push ${{ env.ECR_IMAGE_URI }}

      # Security Scanning
      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@v0.30.0
        with:
          image-ref: ${{ env.ECR_IMAGE_URI }}
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "trivy-results.sarif"

      # Verification
      - name: Verify ECR deployment
        run: |
          echo "Successfully deployed to: ${{ env.ECR_IMAGE_URI }}"
          aws ecr describe-images \
            --repository-name ${{ env.ECR_REPOSITORY_NAME }} \
            --image-ids imageTag=${{ env.DOCKER_IMAGE_TAG }} \
            --region ${{ env.AWS_REGION }}
